### ISSUE TITLE
Github Actions만으로 가동되는 봇으로 수정하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/rankingbot#15]
현재는 이 봇이 AWS EC2 인스턴스 위에서 실행되고 있습니다.

그러나 모든 동작이 Github Actions 상에서도 가능해 보이며, 이에 따라 도커 관련 부분은 덜어내고 주기적으로 파이썬만 실행하도록 수정합니다.

- [x] 깃헙 액션 작성
- [x] Docker Hub에 있는 랭킹봇 도커 이미지 repository에 사용되지 않음 경고 추가하기
- [x] github repository 세팅에 Deploy Key로 Docker Cloud가 등록되어 있는 것 지우기
- AWS에서 봇 지우기
  - [x] https://github.com/femiwiki/docker-mediawiki/blob/master/bots.yml 수정하고 deploy 하기
  - [x] `bot-secret.env` 도 고치기
- [x] README에 docker badge 삭제
- [x] 봇이 제 시간에 잘 가동되는지 주시하기. 한국 시간 매일 오전 6시에 편집이 있어야 합니다([링크](https://femiwiki.com/index.php?title=%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%ED%99%9C%EB%8F%99%EC%A0%81%EC%9D%B8_%EC%82%AC%EC%9A%A9%EC%9E%90/%EB%8D%B0%EC%9D%B4%ED%84%B0&action=history))

**Comment by lens0021** [comment]
2월 15일에 미리님이 하시던 작업인데 이슈만 따로 만들었습니다 Assign에 놀라지 마세용 :smile:

**Comment by lens0021** [comment]
`RANKINGBOT_PASSWORD` 값 전해드립니다: https://pastebin.com/dXNbFBkW
[miriryu's public key](https://keybase.io/miriryu)로 풀어주세요~

**Comment by miriryu** [comment]
> * github repository 세팅에 Deploy Key로 Docker Cloud가 등록되어 있는 것 지우기

없는데 다른분이 이미 지우신걸까요? 어쨌든 체크할게요.

**Comment by lens0021** [comment]
AWS에서 봇 지우고 내리기는 @love-adela 님께서 진행해주실 수 있을까요? 기한은 없고 그냥 시간되는 때에 해주시면 될 것 같습니다

1. 아래 내용으로 PR 만들기 (혹은 바로 마스터에서 작업 해 주셔도 무방합니다)
    - https://github.com/femiwiki/docker-mediawiki/blob/a6d3f39/bots.yml#L3-L6 삭제하기
    - https://github.com/femiwiki/docker-mediawiki/blob/a6d3f39/configs/bot-secret.sample.env#L1-L2 삭제하기
3. EC2 인스턴스에서 `cd mediawiki && git pull` 실행
4. EC2 인스턴스에서 `docker stack deploy --prune -c ~/mediawiki/bots.yml bots` 실행
5. EC2 인스턴스에서 `vim ~/mediawiki/configs/bot-secret.env` 실행하셔서 마찬가지로 랭킹봇 부분만 지워주세요

**Comment by love-adela** [comment]
상세한 설명에 감동 받았서요!

**Comment by lens0021** [comment]
안 돌아가고 있어서 보니까 경로가 잘못되어 이동했습니다 lol
(`.github/rank.yml` → `.github/workflows/rank.yml`) https://github.com/femiwiki/rankingbot/commit/46578af

**Comment by lens0021** [comment]
왜 작동을 안 하는걸까요?ㅠㅠ

**Comment by lens0021** [comment]
https://github.com/femiwiki/rankingbot/commit/db42dcf 얘는 잘 돕니다 왜 기존 yml은 액션으로 실행되지 않을까요???

**Comment by lens0021** [comment]
대문에다가 갱신 안되고 있다고 주의문 달아놓을게요

**Comment by miriryu** [comment]
이제 잘 되는것 같습니다. 이슈 닫습니다.

**Comment by simnalamburt** [comment]
와아아
